### PR TITLE
Change white list to allowed list

### PR DESCRIPTION
**Pull request by come-maiz**

### CODE REVIEW

**Comment by TheDZhon** [comment]
Hey, thank you for participating here :wave: 

Could you please provide a rationale behind the proposed renaming?

P.S. I must say that up-to-date code relies on the `develop` branch and it follows the recently published proposal closely (https://research.lido.fi/t/lip-17-mev-boost-relays-whitelist-for-lido/2885).

**Comment by come-maiz** [comment]
I proposed the same changes on the lip:
https://github.com/lidofinance/lido-improvement-proposals/pull/38

White doesn't mean good. White doesn't mean allowed. This change makes the intention more accurate.

Donna Haraway says that it matters what words we use to create worlds. In here we are creating a new world that is not meant to be, so we have a lot of opportunities to make that world as we dream it. These details matter, they are not small.

More at the personal level, I don't want Flashbots to be in a whitelist, I want Flashbots to be in an allow list :)

If you want to discuss further, I'm thrilled about these topics. Otherwise, I'm just leaving here my suggestion and will let you decide what to do with it.

**Comment by TheDZhon** [comment]
@come-maiz I got your point and appreciate it since we are building together (and with Flashbots :robot: in this particular case) for good.

We have approached the audit team to request the renaming sub-iteration (because they already had a walkthrough round), I hope we can try to catch up on this and deliver the changes in time.

**Comment by arwer13** [comment]
Closing in favour of #9 which updates the up-to-date branch

**Review by robledo6 — APPROVED** [review]

**Pull request closed without merging**
